// ── モックデータ ──
// MCP 連携前の開発用。実データの構造に合わせたリアルなモックデータ
// D365 Update Briefing 出力を参考に構成

import { UpdateItem } from "./types";

export const MOCK_UPDATES: Record<string, UpdateItem[]> = {
  "d365-fo": [
    {
      id: "mc-1181915",
      title: "Dataverse / D365 ストレージ容量・権限変更",
      severity: "breaking",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "Dataverse ストレージ容量の計算方法と権限モデルが変更されます。既存の容量見積もり・課金設計に影響があります。",
      impact: "Dynamics 365 Apps / Microsoft Dataverse（Sales / Service / FO 混在環境）",
      actionRequired: "ストレージ見積もり・課金説明の前提が変更。容量計算・割当の再確認が必要",
      source: "message-center",
      sourceId: "MC1181915",
      sourceUrl: "https://admin.microsoft.com/AdminPortal/Home#/MessageCenter/:/messages/MC1181915",
      date: "2025-12-15",
    },
    {
      id: "mc-fo-license",
      title: "FO ライセンス通知・強制適用スケジュール変更",
      severity: "breaking",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "未ライセンスユーザーへのアクセス遮断が段階的に強制適用されます。",
      impact: "Dynamics 365 Finance & Operations 全環境",
      actionRequired: "10.0.44 以降へのアップグレード前提設計の確認。User Security Governance (USG) の設定確認",
      source: "message-center",
      sourceId: "MC-FO-LIC-2025",
      date: "2025-09-01",
      deadline: "2025-11-01",
    },
    {
      id: "mc-fo-1046",
      title: "FO サービスアップデート通知（10.0.46）",
      severity: "new-feature",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "Sandbox 環境への自動サービスアップデート（10.0.46）がスケジュールされています。",
      impact: "Dynamics 365 Finance & Operations Sandbox 環境",
      actionRequired: "LCS の Update Settings と Message Center 通知の連動を確認",
      source: "message-center",
      date: "2026-01-15",
    },
    {
      id: "learn-d365-copilot-fo",
      title: "D365 Finance — Copilot によるキャッシュフロー予測",
      severity: "new-feature",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "Copilot を使ったインテリジェントキャッシュフロー予測機能が GA。過去データと AI を組み合わせた予測精度向上。",
      impact: "D365 Finance ユーザー",
      actionRequired: "機能の評価・テスト環境での検証を推奨",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/dynamics365/finance/cash-bank-management/cash-flow-forecasting-copilot",
      date: "2026-01-20",
    },
    {
      id: "learn-d365-fo-perf",
      title: "F&O パフォーマンス最適化ガイド更新",
      severity: "improvement",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "バッチ処理とデータエンティティのパフォーマンスチューニングガイドが更新されました。",
      impact: "F&O 開発者・管理者",
      actionRequired: "ベストプラクティスの確認",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/dynamics365/fin-ops-core/dev-itpro/performance/performance-home-page",
      date: "2026-02-01",
    },
  ],

  "d365-ce": [
    {
      id: "learn-d365-sales-copilot",
      title: "D365 Sales — Copilot & AI エージェント",
      severity: "new-feature",
      product: "Dynamics 365 Customer Engagement",
      productFamily: "Dynamics 365",
      summary: "自律型 AI エージェントが 24x7 でリード調査・エンゲージメントを実行。UIがデータ中心からインサイト中心に刷新。",
      impact: "D365 Sales ユーザー全般",
      actionRequired: "新 UI の評価、AI エージェント機能の検証",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/dynamics365/release-plan/2025wave2/sales/",
      date: "2025-10-01",
    },
    {
      id: "mc-field-service-dep",
      title: "Field Service — Outlook, Teams 連携の廃止",
      severity: "breaking",
      product: "Dynamics 365 Customer Engagement",
      productFamily: "Dynamics 365",
      summary: "Field Service の Outlook アドイン、Teams アプリ、Viva Connections 連携、Planner 連携が廃止されます。",
      impact: "Dynamics 365 Field Service",
      actionRequired: "Microsoft 365 内の新しい Field Service 統合エクスペリエンスに移行",
      source: "message-center",
      sourceUrl: "https://learn.microsoft.com/dynamics365/field-service/deprecations-field-service",
      date: "2025-08-15",
      deadline: "2025-10-30",
    },
    {
      id: "mc-field-service-report",
      title: "Field Service — レポート機能の廃止",
      severity: "breaking",
      product: "Dynamics 365 Customer Engagement",
      productFamily: "Dynamics 365",
      summary: "Resource and Utilization レポート、Work Order Summary レポート等が廃止されます。Microsoft Fabric への移行が必要。",
      impact: "Field Service / Resource Scheduling Optimization / Remote Assist",
      actionRequired: "Microsoft Fabric に移行してレポートを再構築",
      source: "message-center",
      date: "2025-06-01",
      deadline: "2025-08-31",
    },
  ],

  azure: [
    {
      id: "azure-openai-gpt5",
      title: "Azure OpenAI Service — GPT-5 シリーズ GA",
      severity: "new-feature",
      product: "Azure",
      productFamily: "Azure",
      summary: "GPT-5.1 および GPT-5.2 モデルが Azure OpenAI Service で一般提供開始。推論性能が大幅に向上。",
      impact: "Azure OpenAI Service 利用者全般",
      actionRequired: "新モデルの評価・移行計画の策定",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/azure/ai-services/openai/concepts/models",
      date: "2026-01-15",
    },
    {
      id: "azure-functions-v5",
      title: "Azure Functions — .NET 9 サポートおよび v4 ランタイム更新",
      severity: "new-feature",
      product: "Azure",
      productFamily: "Azure",
      summary: ".NET 9 の Azure Functions サポートが GA。v4 ランタイムにパフォーマンス改善と新機能が追加。",
      impact: "Azure Functions ユーザー",
      actionRequired: ".NET 9 への移行検証、ランタイム更新の確認",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/azure/azure-functions/functions-versions",
      date: "2025-11-01",
    },
    {
      id: "azure-aks-retirement",
      title: "AKS — Kubernetes 1.28 サポート終了",
      severity: "breaking",
      product: "Azure",
      productFamily: "Azure",
      summary: "AKS での Kubernetes 1.28 のサポートが終了します。1.29 以降へのアップグレードが必要です。",
      impact: "AKS クラスタで Kubernetes 1.28 を使用中の環境",
      actionRequired: "Kubernetes 1.29+ へのクラスタアップグレード",
      source: "message-center",
      date: "2026-01-10",
      deadline: "2026-03-31",
    },
    {
      id: "azure-monitor-perf",
      title: "Azure Monitor — Log Analytics クエリパフォーマンス改善",
      severity: "improvement",
      product: "Azure",
      productFamily: "Azure",
      summary: "Log Analytics のクエリ実行エンジンが最適化され、大規模データセットでのクエリ速度が最大 3 倍に向上。",
      impact: "Azure Monitor / Log Analytics ユーザー",
      actionRequired: "特になし（自動適用）",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/azure/azure-monitor/logs/query-optimization",
      date: "2026-02-05",
    },
  ],

  m365: [
    {
      id: "mc-m365-copilot-agents",
      title: "M365 Copilot — エージェント機能の拡張",
      severity: "new-feature",
      product: "Microsoft 365",
      productFamily: "Microsoft 365",
      summary: "M365 Copilot でカスタムエージェントの作成・デプロイが可能に。Declarative Agents と Custom Engine Agents をサポート。",
      impact: "M365 Copilot ライセンスユーザー",
      actionRequired: "エージェント機能の評価、開発者向けドキュメントの確認",
      source: "message-center",
      date: "2025-11-20",
    },
    {
      id: "mc-teams-classic-retirement",
      title: "Teams クラシック (Win/Mac) — 完全廃止",
      severity: "breaking",
      product: "Microsoft 365",
      productFamily: "Microsoft 365",
      summary: "Microsoft Teams クラシッククライアント (Windows/Mac) が完全に廃止されます。新 Teams クライアントへの移行が必須。",
      impact: "Teams クラシックを使用している全ユーザー",
      actionRequired: "全端末で新 Teams クライアントへの移行を完了させる",
      source: "message-center",
      date: "2025-07-01",
      deadline: "2026-01-31",
    },
  ],

  "power-platform": [
    {
      id: "pp-copilot-studio-update",
      title: "Copilot Studio — マルチチャネル統合の強化",
      severity: "new-feature",
      product: "Power Platform",
      productFamily: "Power Platform",
      summary: "Copilot Studio で Teams, Web, SMS, WhatsApp 等のマルチチャネルデプロイが統一 UI で管理可能に。",
      impact: "Copilot Studio / Power Virtual Agents ユーザー",
      actionRequired: "新しいマルチチャネル設定 UI の確認",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/microsoft-copilot-studio/",
      date: "2026-01-28",
    },
    {
      id: "pp-dataverse-storage",
      title: "Dataverse ストレージモデルの変更",
      severity: "breaking",
      product: "Power Platform",
      productFamily: "Power Platform",
      summary: "Dataverse のストレージ容量算出方法と権限モデルが変更。環境ごとの容量割当に影響。",
      impact: "Power Platform / Dataverse 管理者",
      actionRequired: "ストレージ容量の再評価・割当計画の見直し",
      source: "message-center",
      sourceId: "MC1181915",
      date: "2025-12-15",
    },
  ],

  security: [
    {
      id: "sec-entra-mfa",
      title: "Microsoft Entra — MFA の段階的強制適用",
      severity: "breaking",
      product: "Microsoft Security",
      productFamily: "Security",
      summary: "Azure Portal, Entra admin center, Intune admin center へのアクセスに MFA が段階的に強制適用されます。",
      impact: "Azure / Entra / Intune 管理者",
      actionRequired: "全管理者アカウントで MFA を有効化",
      source: "message-center",
      date: "2025-10-15",
      deadline: "2026-03-31",
    },
  ],
};

/** 製品IDに基づいてモックデータを返す */
export function getMockUpdates(productId: string): UpdateItem[] {
  return MOCK_UPDATES[productId] || [];
}
