// ── モックデータ ──
// MCP 連携前の開発用。実データの構造に合わせたリアルなモックデータ
// D365 Update Briefing 出力を参考に構成

import { UpdateItem } from "./types";

export const MOCK_UPDATES: Record<string, UpdateItem[]> = {
  "d365-fo": [
    {
      id: "mc-1181915",
      title: "Dataverse / D365 ストレージ容量・権限変更",
      titleEn: "Dataverse / D365 Storage Capacity & Permission Changes",
      severity: "breaking",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "Dataverse ストレージ容量の計算方法と権限モデルが変更されます。既存の容量見積もり・課金設計に影響があります。",
      summaryEn: "Changes to Dataverse storage capacity calculation methods and permission models. This affects existing capacity estimates and billing design.",
      impact: "Dynamics 365 Apps / Microsoft Dataverse（Sales / Service / FO 混在環境）",
      impactEn: "Dynamics 365 Apps / Microsoft Dataverse (Sales / Service / FO mixed environments)",
      actionRequired: "ストレージ見積もり・課金説明の前提が変更。容量計算・割当の再確認が必要",
      actionRequiredEn: "Storage estimation and billing assumptions have changed. Re-evaluate capacity calculations and allocations.",
      source: "message-center",
      sourceId: "MC1181915",
      sourceUrl: "https://admin.microsoft.com/AdminPortal/Home#/MessageCenter/:/messages/MC1181915",
      date: "2026-02-10",
    },
    {
      id: "mc-fo-license",
      title: "FO ライセンス通知・強制適用スケジュール変更",
      titleEn: "FO License Notification & Enforcement Schedule Changes",
      severity: "breaking",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "未ライセンスユーザーへのアクセス遮断が段階的に強制適用されます。",
      summaryEn: "Access blocking for unlicensed users will be gradually enforced.",
      impact: "Dynamics 365 Finance & Operations 全環境",
      impactEn: "All Dynamics 365 Finance & Operations environments",
      actionRequired: "10.0.44 以降へのアップグレード前提設計の確認。User Security Governance (USG) の設定確認",
      actionRequiredEn: "Verify upgrade prerequisites for 10.0.44+. Confirm User Security Governance (USG) settings.",
      source: "message-center",
      sourceId: "MC-FO-LIC-2025",
      date: "2026-02-05",
      deadline: "2026-04-01",
    },
    {
      id: "mc-fo-1046",
      title: "FO サービスアップデート通知（10.0.46）",
      titleEn: "FO Service Update Notification (10.0.46)",
      severity: "new-feature",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "Sandbox 環境への自動サービスアップデート（10.0.46）がスケジュールされています。",
      summaryEn: "Automatic service update (10.0.46) is scheduled for Sandbox environments.",
      impact: "Dynamics 365 Finance & Operations Sandbox 環境",
      impactEn: "Dynamics 365 Finance & Operations Sandbox environments",
      actionRequired: "LCS の Update Settings と Message Center 通知の連動を確認",
      actionRequiredEn: "Verify LCS Update Settings and Message Center notification integration.",
      source: "message-center",
      date: "2026-02-01",
    },
    {
      id: "learn-d365-copilot-fo",
      title: "D365 Finance — Copilot によるキャッシュフロー予測",
      titleEn: "D365 Finance — Cash Flow Forecasting with Copilot",
      severity: "new-feature",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "Copilot を使ったインテリジェントキャッシュフロー予測機能が GA。過去データと AI を組み合わせた予測精度向上。",
      summaryEn: "Intelligent cash flow forecasting with Copilot is now GA. Improved prediction accuracy by combining historical data and AI.",
      impact: "D365 Finance ユーザー",
      impactEn: "D365 Finance users",
      actionRequired: "機能の評価・テスト環境での検証を推奨",
      actionRequiredEn: "Evaluate the feature and test in a sandbox environment.",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/dynamics365/finance/cash-bank-management/cash-flow-forecasting-copilot",
      date: "2026-01-20",
    },
    {
      id: "learn-d365-fo-perf",
      title: "F&O パフォーマンス最適化ガイド更新",
      titleEn: "F&O Performance Optimization Guide Updated",
      severity: "improvement",
      product: "Dynamics 365 Finance & Operations",
      productFamily: "Dynamics 365",
      summary: "バッチ処理とデータエンティティのパフォーマンスチューニングガイドが更新されました。",
      summaryEn: "Performance tuning guide for batch processing and data entities has been updated.",
      impact: "F&O 開発者・管理者",
      impactEn: "F&O developers and administrators",
      actionRequired: "ベストプラクティスの確認",
      actionRequiredEn: "Review best practices.",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/dynamics365/fin-ops-core/dev-itpro/performance/performance-home-page",
      date: "2026-02-01",
    },
  ],

  "d365-ce": [
    {
      id: "learn-d365-sales-copilot",
      title: "D365 Sales — Copilot & AI エージェント",
      titleEn: "D365 Sales — Copilot & AI Agents",
      severity: "new-feature",
      product: "Dynamics 365 Customer Engagement",
      productFamily: "Dynamics 365",
      summary: "自律型 AI エージェントが 24x7 でリード調査・エンゲージメントを実行。UIがデータ中心からインサイト中心に刷新。",
      summaryEn: "Autonomous AI agents perform lead research and engagement 24/7. UI refreshed from data-centric to insight-centric.",
      impact: "D365 Sales ユーザー全般",
      impactEn: "All D365 Sales users",
      actionRequired: "新 UI の評価、AI エージェント機能の検証",
      actionRequiredEn: "Evaluate the new UI and verify AI agent capabilities.",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/dynamics365/release-plan/2025wave2/sales/",
      date: "2026-02-03",
    },
    {
      id: "mc-field-service-dep",
      title: "Field Service — Outlook, Teams 連携の廃止",
      titleEn: "Field Service — Outlook & Teams Integration Retirement",
      severity: "breaking",
      product: "Dynamics 365 Customer Engagement",
      productFamily: "Dynamics 365",
      summary: "Field Service の Outlook アドイン、Teams アプリ、Viva Connections 連携、Planner 連携が廃止されます。",
      summaryEn: "Field Service Outlook add-in, Teams app, Viva Connections integration, and Planner integration will be retired.",
      impact: "Dynamics 365 Field Service",
      impactEn: "Dynamics 365 Field Service",
      actionRequired: "Microsoft 365 内の新しい Field Service 統合エクスペリエンスに移行",
      actionRequiredEn: "Migrate to the new Field Service integration experience within Microsoft 365.",
      source: "message-center",
      sourceUrl: "https://learn.microsoft.com/dynamics365/field-service/deprecations-field-service",
      date: "2026-01-25",
      deadline: "2026-04-30",
    },
    {
      id: "mc-field-service-report",
      title: "Field Service — レポート機能の廃止",
      titleEn: "Field Service — Reporting Features Retirement",
      severity: "breaking",
      product: "Dynamics 365 Customer Engagement",
      productFamily: "Dynamics 365",
      summary: "Resource and Utilization レポート、Work Order Summary レポート等が廃止されます。Microsoft Fabric への移行が必要。",
      summaryEn: "Resource and Utilization reports, Work Order Summary reports, and others will be retired. Migration to Microsoft Fabric is required.",
      impact: "Field Service / Resource Scheduling Optimization / Remote Assist",
      impactEn: "Field Service / Resource Scheduling Optimization / Remote Assist",
      actionRequired: "Microsoft Fabric に移行してレポートを再構築",
      actionRequiredEn: "Migrate to Microsoft Fabric and rebuild reports.",
      source: "message-center",
      date: "2026-01-20",
      deadline: "2026-03-31",
    },
  ],

  azure: [
    {
      id: "azure-openai-gpt5",
      title: "Azure OpenAI Service — GPT-5 シリーズ GA",
      titleEn: "Azure OpenAI Service — GPT-5 Series GA",
      severity: "new-feature",
      product: "Azure",
      productFamily: "Azure",
      summary: "GPT-5.1 および GPT-5.2 モデルが Azure OpenAI Service で一般提供開始。推論性能が大幅に向上。",
      summaryEn: "GPT-5.1 and GPT-5.2 models are now generally available on Azure OpenAI Service with significantly improved reasoning performance.",
      impact: "Azure OpenAI Service 利用者全般",
      impactEn: "All Azure OpenAI Service users",
      actionRequired: "新モデルの評価・移行計画の策定",
      actionRequiredEn: "Evaluate new models and plan migration.",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/azure/ai-services/openai/concepts/models",
      date: "2026-01-15",
    },
    {
      id: "azure-functions-v5",
      title: "Azure Functions — .NET 9 サポートおよび v4 ランタイム更新",
      titleEn: "Azure Functions — .NET 9 Support & v4 Runtime Update",
      severity: "new-feature",
      product: "Azure",
      productFamily: "Azure",
      summary: ".NET 9 の Azure Functions サポートが GA。v4 ランタイムにパフォーマンス改善と新機能が追加。",
      summaryEn: ".NET 9 support for Azure Functions is now GA. Performance improvements and new features added to the v4 runtime.",
      impact: "Azure Functions ユーザー",
      impactEn: "Azure Functions users",
      actionRequired: ".NET 9 への移行検証、ランタイム更新の確認",
      actionRequiredEn: "Verify migration to .NET 9 and review runtime updates.",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/azure/azure-functions/functions-versions",
      date: "2026-01-28",
    },
    {
      id: "azure-aks-retirement",
      title: "AKS — Kubernetes 1.28 サポート終了",
      titleEn: "AKS — Kubernetes 1.28 End of Support",
      severity: "breaking",
      product: "Azure",
      productFamily: "Azure",
      summary: "AKS での Kubernetes 1.28 のサポートが終了します。1.29 以降へのアップグレードが必要です。",
      summaryEn: "Support for Kubernetes 1.28 on AKS will end. Upgrade to 1.29 or later is required.",
      impact: "AKS クラスタで Kubernetes 1.28 を使用中の環境",
      impactEn: "Environments running Kubernetes 1.28 on AKS clusters",
      actionRequired: "Kubernetes 1.29+ へのクラスタアップグレード",
      actionRequiredEn: "Upgrade clusters to Kubernetes 1.29+.",
      source: "message-center",
      date: "2026-01-10",
      deadline: "2026-03-31",
    },
    {
      id: "azure-monitor-perf",
      title: "Azure Monitor — Log Analytics クエリパフォーマンス改善",
      titleEn: "Azure Monitor — Log Analytics Query Performance Improvement",
      severity: "improvement",
      product: "Azure",
      productFamily: "Azure",
      summary: "Log Analytics のクエリ実行エンジンが最適化され、大規模データセットでのクエリ速度が最大 3 倍に向上。",
      summaryEn: "The Log Analytics query execution engine has been optimized, improving query speed on large datasets by up to 3x.",
      impact: "Azure Monitor / Log Analytics ユーザー",
      impactEn: "Azure Monitor / Log Analytics users",
      actionRequired: "特になし（自動適用）",
      actionRequiredEn: "No action required (applied automatically).",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/azure/azure-monitor/logs/query-optimization",
      date: "2026-02-05",
    },
  ],

  m365: [
    {
      id: "mc-m365-copilot-agents",
      title: "M365 Copilot — エージェント機能の拡張",
      titleEn: "M365 Copilot — Agent Capabilities Expansion",
      severity: "new-feature",
      product: "Microsoft 365",
      productFamily: "Microsoft 365",
      summary: "M365 Copilot でカスタムエージェントの作成・デプロイが可能に。Declarative Agents と Custom Engine Agents をサポート。",
      summaryEn: "M365 Copilot now supports creating and deploying custom agents. Supports Declarative Agents and Custom Engine Agents.",
      impact: "M365 Copilot ライセンスユーザー",
      impactEn: "M365 Copilot licensed users",
      actionRequired: "エージェント機能の評価、開発者向けドキュメントの確認",
      actionRequiredEn: "Evaluate agent capabilities and review developer documentation.",
      source: "message-center",
      date: "2026-02-08",
    },
    {
      id: "mc-teams-classic-retirement",
      title: "Teams クラシック (Win/Mac) — 完全廃止",
      titleEn: "Teams Classic (Win/Mac) — Full Retirement",
      severity: "breaking",
      product: "Microsoft 365",
      productFamily: "Microsoft 365",
      summary: "Microsoft Teams クラシッククライアント (Windows/Mac) が完全に廃止されます。新 Teams クライアントへの移行が必須。",
      summaryEn: "Microsoft Teams classic client (Windows/Mac) will be fully retired. Migration to the new Teams client is required.",
      impact: "Teams クラシックを使用している全ユーザー",
      impactEn: "All users still on Teams classic",
      actionRequired: "全端末で新 Teams クライアントへの移行を完了させる",
      actionRequiredEn: "Complete migration to the new Teams client on all devices.",
      source: "message-center",
      date: "2026-01-18",
      deadline: "2026-03-31",
    },
  ],

  "power-platform": [
    {
      id: "pp-copilot-studio-update",
      title: "Copilot Studio — マルチチャネル統合の強化",
      titleEn: "Copilot Studio — Multi-Channel Integration Enhancement",
      severity: "new-feature",
      product: "Power Platform",
      productFamily: "Power Platform",
      summary: "Copilot Studio で Teams, Web, SMS, WhatsApp 等のマルチチャネルデプロイが統一 UI で管理可能に。",
      summaryEn: "Copilot Studio now supports managing multi-channel deployments (Teams, Web, SMS, WhatsApp, etc.) through a unified UI.",
      impact: "Copilot Studio / Power Virtual Agents ユーザー",
      impactEn: "Copilot Studio / Power Virtual Agents users",
      actionRequired: "新しいマルチチャネル設定 UI の確認",
      actionRequiredEn: "Review the new multi-channel configuration UI.",
      source: "microsoft-learn",
      sourceUrl: "https://learn.microsoft.com/microsoft-copilot-studio/",
      date: "2026-01-28",
    },
    {
      id: "pp-dataverse-storage",
      title: "Dataverse ストレージモデルの変更",
      titleEn: "Dataverse Storage Model Changes",
      severity: "breaking",
      product: "Power Platform",
      productFamily: "Power Platform",
      summary: "Dataverse のストレージ容量算出方法と権限モデルが変更。環境ごとの容量割当に影響。",
      summaryEn: "Changes to Dataverse storage capacity calculation methods and permission model. Affects capacity allocation per environment.",
      impact: "Power Platform / Dataverse 管理者",
      impactEn: "Power Platform / Dataverse administrators",
      actionRequired: "ストレージ容量の再評価・割当計画の見直し",
      actionRequiredEn: "Re-evaluate storage capacity and review allocation plans.",
      source: "message-center",
      sourceId: "MC1181915",
      date: "2026-02-12",
    },
  ],

  security: [
    {
      id: "sec-entra-mfa",
      title: "Microsoft Entra — MFA の段階的強制適用",
      titleEn: "Microsoft Entra — Phased MFA Enforcement",
      severity: "breaking",
      product: "Microsoft Security",
      productFamily: "Security",
      summary: "Azure Portal, Entra admin center, Intune admin center へのアクセスに MFA が段階的に強制適用されます。",
      summaryEn: "MFA will be progressively enforced for access to Azure Portal, Entra admin center, and Intune admin center.",
      impact: "Azure / Entra / Intune 管理者",
      impactEn: "Azure / Entra / Intune administrators",
      actionRequired: "全管理者アカウントで MFA を有効化",
      actionRequiredEn: "Enable MFA on all administrator accounts.",
      source: "message-center",
      date: "2026-01-22",
      deadline: "2026-03-31",
    },
  ],
};

/** 製品IDに基づいてモックデータを返す */
export function getMockUpdates(productId: string): UpdateItem[] {
  return MOCK_UPDATES[productId] || [];
}
